# -*- coding: utf-8 -*-
"""Week6_IMGProc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VwvweoDAo9BpzNE7IsB2rk2RiOU-AWfY
"""

# Commented out IPython magic to ensure Python compatibility.
#tensorflow and tf.keras
import tensorflow as tf
from tensorflow import keras 

#helper libraries
import numpy as np

# %matplotlib inline
from matplotlib import pyplot as plt
import math



#Micks session example

# randomly initialise an image 10 * 10 pixels
#my_array = np.random.random((20,30))

# Also use 'full' or 'ones' or 'zeros'
# y = np.zeros((10,10)) # also try 'full((10,10),0.5)' or 'ones'

# cmap sets the colourmap - https://matplotlib.org/examples/color/colormaps_reference.html
# cmap is ignored for datasets with rank of 3 or 4, as these are assumed to be RGB(a)
# interpolation is used when the number of pixels in the array
# is such that it can't be shown properly given the size of the plot
# you need to set the lower and upper limits with clim !!!

#plt.imshow(my_array,  cmap='gray', clim=(0,1))
#plt.show()

#print(tf.__version__)

classNames = ['Tshirt/top', 'Trousers', 'Pullover', 'Dress', 'Coat',
              'Sandal','Shirt', 'Sneaker', 'Bag', 'Ankle boot']
#60,000 images all 28x28 
#train_images.shape

#6000
#len(train_labels)

#array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)
#train_labels

#test data set contains 10,000 images all 28x28
#test_images.shape


#plt.figure()
#plt.imshow(train_images[0]) #0: ankle boot 1:T-shirt 2:shirt etc...
#plt.colorbar()
#plt.gca().grid(False)

fashion_mnist = keras.datasets.fashion_mnist

#fashion mnist has 10 classes of data 0:Tshirt/top 1:Trousers 2:Pullover 3:Dress 4:Coat 5:Sandal 6:shirt 7:Sneaker 8:Bag 9:Ankle boot
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images = train_images / 255.0

test_images = test_images / 255.0

plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    plt.xlabel(classNames[train_labels[i]])
plt.show()


#             Building the model.


model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)), # transforms the images to a one way dimensional array
    keras.layers.Dense(128, activation='relu'), 
    keras.layers.Dense(10)
])


model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])


model.fit(train_images, train_labels, epochs=1) # training the model 10 times 


test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\n Accuracy:', test_acc, '%')


# Grab an image from the test dataset.
img = test_images[1]
print(img.shape)

# Add the image to a batch where it's the only member.
img = (np.expand_dims(img,0))

print(img.shape)