# -*- coding: utf-8 -*-
"""NeuralNET_Week5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TFybu9_1cSUv5X3vDJNT7UNKyzNVRBrS
"""

import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd
import sys

#print(tf.__version__)

train_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
target_data = np.array([[0],[1],[1],[0]], "float32")

model = tf.keras.models.Sequential()


#         Add Layers
model.add(tf.keras.layers.Dense(4, input_dim=2, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary accuracy'])

model.summary()

#model.fit(train_data, target_data, nb_epoch=5)